### ISSUE TITLE
Warenkorb nicht gefunden (Ohne Login)

### ISSUE THREAD

**Issue by mahype** [Themekraft/JigoShop-for-BuddyPress#1]
Sofern man nicht angemeldet ist und auf den Warenkorb zugreifen möchte, Zeigt der Shop "Page not found" an.

**Comment by boris-glumpler** [comment]
Dann muss man einfach nur den URL Router ausschalten, wenn die Kunden nicht eingeloggt sind. Dann werden dann eben die Jigoshop eigenen Seiten verwendet.

**Comment by boris-glumpler** [comment]
Neuester Commit schaltet den URL Router und zusammenhängende Funktionen aus. Wenn man ausgeloggt ist, dann werden praktisch die normalen Jigoshop Templates verwendet und die Seiten sind auch in der Nav-Leiste sichtbar.

**Comment by svenl77** [comment]
cool ! ;-)
