### ISSUE TITLE
IE Darstellungsprobleme der Buttons

### ISSUE THREAD

**Issue by mahype** [Themekraft/JigoShop-for-BuddyPress#2]
Irgendwie scheint der IE Darstellungsprobleme mit den Buttons bei den Produkten zu haben.

http://jigo.shabushabu.eu/shop/test-product/

**Comment by boris-glumpler** [comment]
CSS hat das Plugin überhaupt nicht. Wäre ein Punkt für das Jigoshop, bzw. BuddyPress Team, ausser wir packen evtl. noch ein Child Theme zu BP-Default mit ins Plugin
