### ISSUE TITLE
Shop Reiter im Profil

### ISSUE THREAD

**Issue by mahype** [Themekraft/JigoShop-for-BuddyPress#3]
Der Shop Reiter im Profil darf nur für einen selber sichtbar sein. Nicht für andere.

**Comment by boris-glumpler** [comment]
Vergess ich jedesmal, dass das für die Haupt-Menüpunkte ein anderer Key ist als bei Unterpunkten :)

**Comment by boris-glumpler** [comment]
Neuester Commit behebt das Problem.
