### ISSUE TITLE
Copyright ändern

### ISSUE THREAD

**Issue by mahype** [Themekraft/JigoShop-for-BuddyPress#4]
Das Copyright steht noch auf Shabushabu. Da sollte dann Themekraft stehen. Als Author bist Du ja drin.

**Comment by boris-glumpler** [comment]
Nachdem ich den Code geschrieben habe gehört das Copyright automatisch mir und meiner Firma. Solltet ihr mal Code hinzufügen, dann könnt ihr für diesen Teil dann das Copyright auf Themekraft setzen.

**Comment by mahype** [comment]
Das war eine Auftragsarbeit. Wir haben vorher über alles gesprochen. Wir wollen das Plugin hinterher vermarkten und mit dem Copyright können wir das sicherlich nicht. So geht das nicht. Dann müssen wir das Plugin selber bauen. Ruf bitte sobald Du Zeit hast bei Sven Lehnert durch. Hier ist durch Deine Aussage gerade ziemliches Chaos ausgebrochen.

**Comment by boris-glumpler** [comment]
Auftragsarbeiten ändern nichts am Copyright. Wenn ihr z.B. ein WP Theme für einen Kunden erstellt, dann gehört das Copyright immer noch euch, auch wenn ihr dem Kunden das verkauft habt. Das ist besonders bei Software so. Ich hab das aber nochmal mit Stefan durchgesprochen und das Copyright jetzt geändert und den Plugin Author auf BP Shop Dev Team gesetzt mit dem Link zur Github Seite. Mein Name müsste aber drinnen stehen bleiben. Da könnt ihr ja dann einfach eure hinten dran setzten, wenn ihr was an den Funtionen ändert. Chaos wollte ich wirklich nicht verbreiten :) Ich hab heute auch leider sehr wenig Zeit, weils bei mir morgen um 4 Uhr morgens schon los geht. Ich meld mich dann aber nochmal von England aus in den nächsten paar Tagen.
