### ISSUE TITLE
"Thank You" page shown in top navi

### ISSUE THREAD

**Issue by HatdatWp** [Themekraft/JigoShop-for-BuddyPress#5]
http://jigoshop.themekraft.com/
A link to the "Thank You" Page is still provided in the "Checkout" drop down menu.

**Comment by boris-glumpler** [comment]
Yup, that is the view you get for logged-out users. All Jigoshop menu items will disappear once you're logged in. BP-Shop currently does not adjust BP-Default to account for theme issues between BP and Jigoshop.
