### ISSUE TITLE
Order Panding

### ISSUE THREAD

**Issue by svenl77** [Themekraft/JigoShop-for-BuddyPress#8]
Nach der Bezahlung steht die Bestellung auf panding und muss manuell compleated werden damit der Kunde downloaden kann.

Kann man das bei herunter ladbaren Produkten nicht automatisieren so das nach der Bezahlung direkt heruntergeladen werden kann ohne das die Bestellung manuell bearbeitet werden muss?

**Comment by boris-glumpler** [comment]
Ich denke mal, dass das schon automatisch passiert (sollte es zumindest, hab allerdings noch nicht nachgesehen). Wenn man in seinem PayPal Account allerdings keine IPN aktiviert hat, dann kann das System nicht wissen, dass eine Bezahlung durchgegangen ist, weil keine Nachricht kam. Wenn das der Fall ist, dann bleibt nur das Ganze manuell zu machen.

**Comment by mahype** [comment]
Jepp. Allerdings fehlt uns noch eine Notification URL, die wir bei PayPal angeben können. Die URL für den Blog scheint es nicht zu sein.

**Comment by boris-glumpler** [comment]
Das sollte automatisch vom Plugin gesetzt werden. Wenn man IPN und Return in seinem PayPal Account anschaltet gibt man am besten irgendeine URL ein. Egal welche, es muss nur aktiviert sein. Über den PayPal Button kann man dann diese URL überschreiben, was eigentlich automatisch von Jigoshop gemacht werden sollte. Am Besten einfach mal ne Testbestellung über die PayPal Sandbox laufen lasssen, dann weiss mans genau.

**Comment by mahype** [comment]
OK! Daaaaanke Dir! 

Das ganze scheint aber ein PayPal Sandbox Problem zu sein. Bei richtigen Käufen funktionierts ;)

**Comment by svenl77** [comment]
cool ! wird geschlossen, klappt ja ;-)

**Comment by svenl77** [comment]
cool ! wird geschlossen, klappt ja ;-)
